version: '3.9'

services:
  go-app:
    container_name: go-app
    image: go-product-api
    build: .
    ports:
      - 8080:8080
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}