version: '3.9'

services:
  go_db:
    container_name: go_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}